version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dairy_management
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data # Persist DB
      - ./init-db:/docker-entrypoint-initdb.d # 👈 Auto-load .sql file if DB is empty

  api:
    build:
      context: .
      dockerfile: DairyManagement.API/Dockerfile
    container_name: dotnet-api
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=dairy_management;Username=postgres;Password=postgres;

volumes:
  db-data:
